/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Achievement: typeof import('./src/components/student/honors/achievement.vue')['default']
    AchievementCollect: typeof import('./src/components/student/honors/achievement-collect.vue')['default']
    AchievementDetail: typeof import('./src/components/student/honors/AchievementDetail.vue')['default']
    AchievementDetailDialog: typeof import('./src/components/admin/achievement/AchievementDetailDialog.vue')['default']
    AchievementList: typeof import('./src/components/admin/achievement/AchievementList.vue')['default']
    AchievementSettings: typeof import('./src/components/student/honors/AchievementSettings.vue')['default']
    AdminDashboard: typeof import('./src/components/admin/dashboard/AdminDashboard.vue')['default']
    AdminLogin: typeof import('./src/components/admin/login/AdminLogin.vue')['default']
    AiChat: typeof import('./src/components/student/portrait/ai-chat.vue')['default']
    AssignmentDetail: typeof import('./src/components/student/assignments/assignment-detail.vue')['default']
    Assignments: typeof import('./src/components/student/assignments/assignments.vue')['default']
    AuditDialog: typeof import('./src/components/admin/achievement/AuditDialog.vue')['default']
    CertificateOcr: typeof import('./src/components/student/honors/CertificateOcr.vue')['default']
    CollegeActivity: typeof import('./src/components/student/activities/college-activity.vue')['default']
    Consulting: typeof import('./src/components/student/consulting/consulting.vue')['default']
    CoursesPage: typeof import('./src/components/student/courses/CoursesPage.vue')['default']
    DashboardPage: typeof import('./src/components/student/dashboard/DashboardPage.vue')['default']
    DataScreen: typeof import('./src/components/student/stastic/data-screen.vue')['default']
    Feedback: typeof import('./src/components/student/feedback/feedback.vue')['default']
    FeishuQuickImport: typeof import('./src/components/student/honors/FeishuQuickImport.vue')['default']
    FloatingAiAssistant: typeof import('./src/components/common/FloatingAiAssistant.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Jobpage: typeof import('./src/components/student/job/jobpage.vue')['default']
    LoginPage: typeof import('./src/components/student/login/LoginPage.vue')['default']
    PortraitAnalysis: typeof import('./src/components/student/portrait/portrait-analysis.vue')['default']
    PortraitChat: typeof import('./src/components/student/portrait/portrait-chat.vue')['default']
    Resume: typeof import('./src/components/student/resume/resume.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TalentMarket: typeof import('./src/components/student/talent-market/talent-market.vue')['default']
    TeacherDetail: typeof import('./src/components/student/teachers/TeacherDetail.vue')['default']
    Teachers: typeof import('./src/components/student/teachers/teachers.vue')['default']
    VoteSurvey: typeof import('./src/components/student/vote-survey/vote-survey.vue')['default']
  }
}
