/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AchievementDetailDialog: typeof import('./src/components/admin/achievement/AchievementDetailDialog.vue')['default']
    AchievementList: typeof import('./src/components/admin/achievement/AchievementList.vue')['default']
    AdminDashboard: typeof import('./src/components/admin/dashboard/AdminDashboard.vue')['default']
    AdminLogin: typeof import('./src/components/admin/login/AdminLogin.vue')['default']
    AuditDialog: typeof import('./src/components/admin/achievement/AuditDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
