/**
 * 图标索引文件
 * 集中导出所有需要使用的图标，便于在各组件中统一引用
 */

// 从@tabler/icons-vue导入所需图标
// 导航和菜单图标
import {
  IconHome,
  IconChartBar,
  IconBook,
  IconFileText,
  IconUsers,
  IconAward,
  IconMessageCircle,
  IconCalendar,
  IconUser,
  IconLogout,
  IconSettings,
  IconChevronLeft,
  IconChevronRight,
  IconSchool,
  IconFileDescription,
  IconHelpCircle,
  IconCaretDown,
  IconCaretRight,

  // 操作图标
  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconSearch,
  IconRefresh,
  IconDownload,
  IconUpload,
  IconEye,
  IconEyeOff,
  IconCheck,
  IconX,

  // 状态图标
  IconAlertCircle,
  IconInfoCircle,
  IconFile,
  IconAlertTriangle,
  IconCircleCheck as IconCheckCircle,
  IconBulb as IconLightbulb,
  // 其他常用图标
  IconMail,
  IconPhone,
  IconLock,
  IconBell,
  IconStar,
  IconHeart,
  IconThumbUp,
  IconShare,
  IconLink,
  IconExternalLink,
  IconClipboard,
  IconFilter,
  IconSend,

  // 人才市场相关图标
  IconBuilding,
  IconBriefcase,
  IconTrendingUp,
  IconTarget,
  IconMapPin,
  IconClock,
  IconCode,
  IconMusic,
  IconCamera,
  IconDeviceGamepad as IconGamepad,
  IconRobot,
  IconDots as IconMore,
  IconList,
  IconBrain
} from '@tabler/icons-vue'

// 重新导出所有图标
export {
  IconHome,
  IconChartBar,
  IconBook,
  IconFileText,
  IconUsers,
  IconAward,
  IconMessageCircle,
  IconCalendar,
  IconUser,
  IconLogout,
  IconSettings,
  IconChevronLeft,
  IconChevronRight,
  IconSchool,
  IconFileDescription,
  IconHelpCircle,
  IconCaretDown as CaretDown,
  IconCaretRight as CaretRight,

  IconPlus,
  IconMinus,
  IconEdit,
  IconTrash,
  IconSearch,
  IconRefresh,
  IconDownload,
  IconUpload,
  IconEye,
  IconEyeOff,
  IconCheck,
  IconX,

  IconAlertCircle,
  IconInfoCircle,
  IconFile,
  IconAlertTriangle,

  IconMail,
  IconPhone,
  IconLock,
  IconBell,
  IconStar,
  IconHeart,
  IconThumbUp,
  IconShare,
  IconLink,
  IconExternalLink,
  IconClipboard,
  IconFilter,
  IconSend,

  // 业务相关图标
  IconBuilding,
  IconBriefcase,
  IconTrendingUp,
  IconTarget,
  IconMapPin,
  IconClock,
  IconCode,
  IconMusic,
  IconCamera,
  IconCheckCircle,
  IconLightbulb,
  IconRobot,
  IconMore,
  IconList,
  IconBrain
}